version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - .:/workspace
    env_file:
      - .env